
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULT = 16;
  public static final int C_PAREN = 20;
  public static final int O_PAREN = 19;
  public static final int INT = 34;
  public static final int MINOR = 17;
  public static final int O_CBRACKET = 23;
  public static final int MINUS = 15;
  public static final int STATIC = 5;
  public static final int SEMICOLON = 25;
  public static final int AND = 18;
  public static final int S_EXCL = 28;
  public static final int COMMA = 27;
  public static final int CLASS = 8;
  public static final int PLUS = 13;
  public static final int MAIN = 7;
  public static final int IF = 31;
  public static final int THIS = 9;
  public static final int DOT = 26;
  public static final int O_SBRACKET = 21;
  public static final int BOOLEAN = 35;
  public static final int EOF = 0;
  public static final int TRUE = 37;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int VOID = 6;
  public static final int EQ = 14;
  public static final int ELSE = 33;
  public static final int C_CBRACKET = 24;
  public static final int WHILE = 32;
  public static final int PUBLIC = 4;
  public static final int EXTENDS = 3;
  public static final int STRING = 36;
  public static final int FALSE = 38;
  public static final int C_RETURN = 12;
  public static final int PRINT = 2;
  public static final int LENGTH = 11;
  public static final int C_SBRACKET = 22;
  public static final int INTEGER_LITERAL = 30;
  public static final int IDENTIFIER = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PRINT",
  "EXTENDS",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "CLASS",
  "THIS",
  "NEW",
  "LENGTH",
  "C_RETURN",
  "PLUS",
  "EQ",
  "MINUS",
  "MULT",
  "MINOR",
  "AND",
  "O_PAREN",
  "C_PAREN",
  "O_SBRACKET",
  "C_SBRACKET",
  "O_CBRACKET",
  "C_CBRACKET",
  "SEMICOLON",
  "DOT",
  "COMMA",
  "S_EXCL",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "IF",
  "WHILE",
  "ELSE",
  "INT",
  "BOOLEAN",
  "STRING",
  "TRUE",
  "FALSE"
  };
}

